### ISSUE TITLE
[v10] Issues with the Stylesheet's "hidden" and Tailwind

### ISSUE THREAD

**Issue by saibotk** [serebrov/emoji-mart-vue#122]
Hey there!
Thank you for maintaining this package!

With the recent update, the stylesheet includes a global `hidden` class, which breaks frameworks like TailwindCSS that defines its own hidden and relies on its internal order where the class is defined for overwrites etc.

It would be awesome if we could find a solution, so that the component does not expose any global css classes.

Thank you!

**Comment by serebrov** [comment]
@saibotk I've just pushed version 10.0.1 with a fix, please check if it works for you.

**Comment by saibotk** [comment]
Thanks it works now, just tested it.

That was fast, thank you very very much! :rocket:
