### ISSUE TITLE
Category-Bar Icons don't use emoji-size

### ISSUE THREAD

**Issue by jotoeri** [serebrov/emoji-mart-vue#124]
Setting emoji-size e.g. to 16px, the buttons (emoji-mart-anchor) shrink, while the svg within keeps its fixed size of 24px:

![grafik](https://user-images.githubusercontent.com/47433654/116630534-9f9a4780-a953-11eb-8959-857e2755669b.png)

Observed on v10.0.1

**Comment by serebrov** [comment]
@jotoeri I think `emojiSize` and `perLine` are supposed to adjust the picker width, while making it look neat in general should be done with CSS.

I updated the [demo](https://github.com/serebrov/emoji-mart-vue/commit/a1a708ae759d585e7dd3cd08157a9c38f623ef64) with a small picker example which shows the idea:

<img width="1101" alt="Screenshot 2021-05-02 at 17 23 59" src="https://user-images.githubusercontent.com/597640/116816625-60464380-ab6b-11eb-9c06-f1c1437a4873.png">


Here, anchors and bottom preview area are adjusted to smaller emojis with CSS.

**Comment by jotoeri** [comment]
Hmm, interesting concept... I'd have expected it's either consequently finishing with props or consequently css... But well. 🤷‍♂️ 👍
