### ISSUE TITLE
TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by Lzf-Jeff** [serebrov/emoji-mart-vue#131]
Hi, When I try to initialize, I get an error,
I use typescript and vue3.0.
filetype is tsx.
<Picker set="emojione" data={emojiIndex} />
please help me.

**Comment by Lzf-Jeff** [comment]
sorry，I know where I made a mistake.

**Comment by loremru** [comment]
@Lzf-Jeff Could you help with the same issue?

**Comment by Durss** [comment]
In case that can help anyone coming by years later like I, the fix consists of importing from "src" folder:
```js
import { Picker, EmojiIndex } from "emoji-mart-vue-fast/src";
```

**Comment by Lzf-Jeff** [comment]
您好 来信已经收到
