### ISSUE TITLE
 Update  "emoji-datasource" to 7.x.x

### ISSUE THREAD

**Issue by ram-you** [serebrov/emoji-mart-vue#132]
Please update  "emoji-datasource" to latest 7.x.x
 Thank you.

**Comment by serebrov** [comment]
Main [change](https://github.com/iamcal/emoji-data/blob/master/CHANGES.md) in v7: Updated to Emoji 13.1.

Previous major update (Emoji v13): 

* https://github.com/serebrov/emoji-mart-vue/pull/108
* https://github.com/serebrov/emoji-mart-vue/pull/109

**Comment by serebrov** [comment]
We've updated to v14 datasource in #205, closing this issue.
