### ISSUE TITLE
:smiling_face_with_tear: browser is not support ，Can I manually select the emoji version

### ISSUE THREAD

**Issue by youcanping** [serebrov/emoji-mart-vue#133]
:smiling_face_with_tear: browser is not support ，Can I manually select the emoji version

<img width="434" alt="截屏2021-06-28 下午3 59 11" src="https://user-images.githubusercontent.com/30832864/123601415-3be4ab80-d82a-11eb-9073-d6eaa993285f.png">

- https://unicode.org/emoji/charts/full-emoji-list.html
<img width="1167" alt="截屏2021-06-28 下午4 03 53" src="https://user-images.githubusercontent.com/30832864/123601607-777f7580-d82a-11eb-983e-2ce1f0fdb4fe.png">

**Comment by serebrov** [comment]
@youcanping Sorry for late reply. I am not sure if I understand the question. If you are using native emojis, it still can be problematic and depends on the operating system and browser.

The reliable solution is to use image-based emoji, see also #71, #72, #78.

**Comment by serebrov** [comment]
Closing, for now, feel free to provide more details and reopen if this is a bug.

**Comment by youcanping** [comment]
thinks
