### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getSkin')

### ISSUE THREAD

**Issue by productdevbook** [serebrov/emoji-mart-vue#155]
https://user-images.githubusercontent.com/38668796/144252476-e2183ad0-7324-4f16-8c7b-eec17f72773d.mp4

**Comment by serebrov** [comment]
Thanks for the video, but I can not reproduce the issue.
I need a step-by-step sequence of actions to get to the issue. Good to also make sure it is reproduced in the [demo app](https://serebrov.github.io/emoji-mart-vue/) or provide a minimal code example.
