### ISSUE TITLE
do I have to initialize the emoji data manually in the emoji component each time?

### ISSUE THREAD

**Issue by stalkercn** [serebrov/emoji-mart-vue#160]
each `index = new EmojiIndex(emojiData)` takes about 50ms, if I have 50 emojis, it will take 2.5s to render.

**Comment by serebrov** [comment]
@stalkercn No, you do not have to initialize it many times. It supposed to be initialized only once and re-used by components.

The only case to create another index is when a different set of emojis needed (for example, emojis can be [filtered](https://github.com/serebrov/emoji-mart-vue/blob/9fda9b72456992f507b1167330349faa4cd4f45c/docs/app.vue#L215-L220)).
