### ISSUE TITLE
Does this package actually work on Vue 3.2.20

### ISSUE THREAD

**Issue by tannert44** [serebrov/emoji-mart-vue#172]
Hello, 

I just wanted to confim this was user error. I installed the package on Vue 3.2.20 and quasar 2.0.  

```
<template>
  <q-menu touch-position :target="targetElement">
    <picker :data="emojiIndex" :set="emojiSet" @select="emitEmjoiSelected"></picker>
  </q-menu>
</template>

<script>
import { defineComponent, ref, computed, watch } from 'vue'
import data from "emoji-mart-vue-fast/data/all.json"
import "emoji-mart-vue-fast/css/emoji-mart.css"
import { Picker, EmojiIndex } from "emoji-mart-vue-fast"


export default defineComponent({
  name: 'EmojiPicker',
  props: {
    emojiSet: {
      type: String,
      default:"twitter"
    },
    targetElement: {
      type: String
    }
  },
  emits: ["emojiSelected"],
  components: {
    Picker
  },
  setup (props, context) {
    const emitEmjoiSelected =  (emoji) => {
      context.emit('emojiSelected', emoji)
    }
    const emojiIndex = ref(new EmojiIndex(data))
    return {
      emojiIndex: emojiIndex,
      emitEmjoiSelected: emitEmjoiSelected
    }
  }
})
</script>

<style lang="sass" scoped>
.emoji-mart-body .emoji-type-image.emoji-set-twitter 
	background-image: url(/img/twitter-5.0.1-sheets-256-64.png)
</style>
```

I've also tried taking this out of q-menu and just putting it on a page. Anytime I do it breaks the app. Do you see anything I am doing wrong?

The error message is  "Cannot read properties of undefined (reading '_c')", and it's showing this in minified version of the code, which is in your picker class:

```
getCategoryComponent: function(e) {
                        var t = this.$refs["categories_" + e];
                        return t && "0"in t ? t[0] : t
                    }
```

**Comment by serebrov** [comment]
It is hard to say without testing it locally, some things to check:

* I think the `ref` around `new EmojiIndex(data)` might not be needed as the emoji data is static (not sure if it can cause the error though)
* There are some typos with `emjoi` instead of "emoji"
* There is a demo project with Vue 3: https://github.com/serebrov/emoji-mart-vue3-demo, although I did it awhile ago and did not test with recent Vue, might be worth trying that project to see if the error can be reproduced there

**Comment by tannert44** [comment]
Thanks for taking a look. I moved the emojiIndex to ref shooting in the dark. Originally I had it where you have it in your samples. Neither worked. I fixed the typos, all though they were consistent across the file. Still not working. I'll take a look at the vue 3 demo. If I find anything I'll let ya know.

**Comment by tannert44** [comment]
Unfortunately updating the import to src still does not fix the problem. Same error. I'll pull down and see if I can figure out what's going on.

**Comment by tannert44** [comment]
You can close this. I was a major version behind on npm on my machine. I was on 7. Upgraded to 8 and it worked.
