### ISSUE TITLE
Some emojis is missing

### ISSUE THREAD

**Issue by KingJardon** [serebrov/emoji-mart-vue#183]
Flag is short for flag

**Comment by serebrov** [comment]
Not enough information, but probably related to these discussions: #78, #71, #72, #133.

**Comment by KingJardon** [comment]
It's not an image, it's a shorthand

**Comment by KingJardon** [comment]
https://hub.textile.io/ipfs/bafkreigaw64hstmqomgqn2rot2h6zl6uxlzipdsiqbaa6wyh2yp2vutdym

**Comment by serebrov** [comment]
I do not understand what this issue is about. If you are still having the problem, please open a new issue and provide more details about it.
