### ISSUE TITLE
Huge delay when hover a emoji in Picker

### ISSUE THREAD

**Issue by 0xdapy** [serebrov/emoji-mart-vue#232]
Hello, recently I started to use your library, but recently I have encountered a huge delay in the hover function of each emoji `onEmojiEnter()`, here is a video that shows this delay:

https://user-images.githubusercontent.com/113697875/190650506-9ece797c-2c01-48d0-af5f-532510db87a4.mp4

As you can see in the video, the hover function takes a long time to load, in my case I had cases where the delay was up to 100ms, when I had the mouse hovering over several emojis the preview didn't even change.

**Comment by serebrov** [comment]
Does it work like this if you close the Vue inspector? Or maybe some browser extension affects the speed?

I just tried and it works good for me:


https://user-images.githubusercontent.com/597640/196013930-0f874778-652e-4e08-bc21-a4fa1751653f.mov

**Comment by serebrov** [comment]
Closing, not enough details to reproduce of fix this issue.

If you have more information about it, please feel free to provide it and reopen the issue.
