### ISSUE TITLE
Attempting to press Enter after an unfruitful search throws some errors

### ISSUE THREAD

**Issue by kpwbo** [serebrov/emoji-mart-vue#263]
Hello! :smiley:

Steps to reproduce:
1. Go to the demo page: https://serebrov.github.io/emoji-mart-vue3-demo/
2. Open the browser's console to see the error at step 4.
3. Enter `asd` in the search bar of the picker. No emojis should be found.
4. Press Enter while in the search bar. Two errors should be displayed in the browser's console.

<details>
<summary>Screenshot of the errors</summary>

![image](https://user-images.githubusercontent.com/5074608/232881200-d3cbef24-7ad6-4727-9710-864ed11cf36f.png)
</details>

Ideally, there should be no errors thrown.

Thanks!

**Comment by serebrov** [comment]
@kpwbo Thanks! I fixed the problem and published release 12.0.3.
