### ISSUE TITLE
Emoji component does not display emoji

### ISSUE THREAD

**Issue by darivs** [serebrov/emoji-mart-vue#44]
Good morning,

I am happy to found a distribution of the emoji mart which picker is way faster than jm-davids one. And I appreciate that you filled the docs! But your emoji component does not seem to work properly, it doesn't show up. I followed your instructions on the docs, but without success.

```javascript
import { Emoji } from "emoji-mart-vue-fast";`
...
export default {
    components: {
        Emoji
    }
...
```

```html
<span>BEFORE</span>
<emoji emoji="santa" set="messenger" :size="16"/>
<span>AFTER</span>
```

![image](https://user-images.githubusercontent.com/19775319/56790994-4e0bcf00-6806-11e9-90b8-7b5479f04c5a.png)

DOM:
```html
<span>BEFORE</span>
<span class="emoji-mart-emoji" size="16">
  <span class="emoji-set-messenger emoji-type-image" style="background-position: 15.69% 37.25%;"></span>
</span>
<span>AFTER</span>
```

Maybe you know the reason!

Have a nice day

**Comment by serebrov** [comment]
@darivs hi, have you included the CSS? Since you are using the "messenger" image version, you need to also import the css `import 'emoji-mart-vue-fast/css/emoji-mart.css'`.

You can also compare with the demo app in this repository (https://github.com/serebrov/emoji-mart-vue/tree/master/docs) or standalone (https://github.com/serebrov/emoji-mart-vue-test). Live version is here - http://serebrov.github.com/emoji-mart-vue, there is a button with single emoji (not the picker) at the top, near the "show / hide the picker" button.

**Comment by darivs** [comment]
@serebrov Yes, I imported the css in my main.js and the messenger emojis got displayed in my picker component properly. I also compared to your demo app. With the way you use to display the single emoji on the button, I get the emoji displayed, but you don't use your Emoji component.

```javascript
import data from "emoji-mart-vue-fast/data/all.json";
import { EmojiIndex } from "emoji-mart-vue-fast"
let index = new EmojiIndex(data);

export default {
    data() {
        return {
            index: index
        }
    }
},
computed: {
    smile() {
        // Static emoji example
        let emoji = index.findEmoji(":smile:");
        // Note, that position in the emoji sheet is calculated by
        // `emoji` object
        let style = `background-position: ${emoji.getPosition()}; background-image: url(https://unpkg.com/emoji-datasource-emojione@4.0.4/img/emojione/sheets-256/64.png); width: 24px; height: 24px; display: inline-block; background-size: 5200%`;
        return `<div class='emoji' style="${style}"></div>`;
    }
}
```
```HTML
<span v-html="smile"></span>
```

That does not seem to be the proper way, does it?

**Comment by serebrov** [comment]
@darivs right, that example is to show how to use `EmojiIndex` on its own, without components.
The `Emoji` behavior is a bug, I am working on a fix.

**Comment by serebrov** [comment]
@darivs please check the new version, 5.4.12, it should work like this:

```
    <div class="row">
      <emoji emoji=":santa::skin-tone-3:" :size="32" />
      <emoji emoji="santa" set="emojione" :size="32" />
      <emoji :emoji="santaEmojiObject" :size="32" />
    </div>
```

First two examples are using emoji as a string, the last example is to set emoji as an object, in this case you also need to create the object, something like this:

```
  computed: {
    santaEmojiObject() {
      return index.findEmoji(':santa:')
    },
  },
```

I also update the demo app (https://serebrov.github.io/emoji-mart-vue/) and a standalone example (https://github.com/serebrov/emoji-mart-vue-test) to include `Emoji`s with `:santa:`.

**Comment by darivs** [comment]
Thank you very much for the maintenance, now it works!

**Comment by focux** [comment]
I was about to open an issue about this, glad this is already fixed. Thank you so much for your work and improvements in this library @serebrov.
