### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by DCsunset** [serebrov/emoji-mart-vue#46]
Hello, 

First thanks for your work to make the component much faster.
Now the library doesn't seem to support Server Side Rendering and it will throw the error "Window is not defined".

Is there any plan to support this plugin in SSR mode?

Thanks in advance.

**Comment by serebrov** [comment]
@DCsunset does it work with the original library? Can you provide some minimal code example to demonstrate the problem?

I personally didn't use SSR with Vue, so need some example that I can run to reproduce the issue.

**Comment by DCsunset** [comment]
@serebrov,
 I have made a demo repository using Nuxt.js to reproduce the problem:
<https://github.com/DCsunset/emoji-mart-vue-demo>

First `npm install` and next run `npm run dev`.
Then you can visit <http://localhost:3000> to see the error.

**Comment by serebrov** [comment]
@DCsunset the cause of the "window is not defined" is this webpack issue - https://github.com/webpack/webpack/issues/6784, it worked in webpack 3, but doesn't in webpack 4.

I've applied the fix suggested in comments, now the "window is undefined" is gone, please switch to v5.4.13 to get the update. 

But I am not closing the issue yet, as there is now a "document is not defined" error. Not sure if this is the same as reported here for the original library - https://github.com/jm-david/emoji-mart-vue/issues/21, I'll check that later.

**Comment by serebrov** [comment]
@DCsunset I've just pushed one more version - `5.4.14` with one more fix, now your demo app works for me, please check on your side.

**Comment by DCsunset** [comment]
Now it works under SSR. Thank you very much!
