### ISSUE TITLE
Exclude of categories not correctly working

### ISSUE THREAD

**Issue by ithr0n** [serebrov/emoji-mart-vue#60]
`new EmojiIndex(data, { exclude: ['recent'] })` does not exclude the recent category.
Instead, `new EmojiIndex(data, { exclude: ['people'] })` excludes the recent and people category.

Additionally, after showing the Picker the first category is shown (correctly), but the second category is selected in the view. For example, with every category enabled it shows the recent category, but the people category is selected.

**Comment by serebrov** [comment]
@ithr0n Thanks, I was able to reproduce the bug with excluding the 'recent' category, and I'll release a fix soon.
Alternative way is to set `recent` explicitly, as this is a "special" category loaded from the local storage:  `EmojiIndex(data, {recent: []})`.

In my testing, the `recent` could disappear when `people` is excluded if recent only has emojis from people. If I add emojis from other categories, then `recent` is displayed.

Regarding the shifted active category - this comes from the virtual scroller and I don't see a simple fix here. You try the `StaticPicker` component that doesn't use virtual scroller.

There is a PR in virtual scroller repository that would fix this issue - https://github.com/Akryum/vue-virtual-scroller/pull/115, but it is there for a long time, not sure if it get's merged any time soon.

**Comment by serebrov** [comment]
Published version `6.1.2` with the fix to npm.

**Comment by serebrov** [comment]
Closing, hopefully it works now.
