### ISSUE TITLE
Reseting emoji picker

### ISSUE THREAD

**Issue by aldinezi** [serebrov/emoji-mart-vue#63]
First of all, thank you for this awesome fork and amazing fast component.

As I am using single instance of Picker with Popper, I would like it to start fresh every time it's opened. I was wandering if I could make Picker to reset scroll and return to the first category after selecting emoji. 

I am also willing to help and create a PR modifying `onEmojiClick` method to change the `activeCategory`.

**Comment by serebrov** [comment]
@aldinezi the default behavior seems to be to start fresh, see the demo app - https://serebrov.github.io/emoji-mart-vue/, if you scroll the picker down and then click the "Show / hide the picker" button, it will be scrolled all the way to the top again when it shows.

Same behavior is with the "QDialog Example" that shows picker in the popup - it is always scrolled to the top when it opens.

**Comment by aldinezi** [comment]
Yes, indeed. But I am using single instance, inside popper which is controlled with v-show, so it's is not starting fresh.

**Comment by serebrov** [comment]
@aldinezi ah, I see, here is a quick solution that works for me in demo app.

The idea is to call `onAnchorClick` to emulate the click on the first category.

```
<template>
  <div class="app">
    <div class="row" v-show="flagsVisible">
      <Picker
        :native="true"
        emoji="flag-tf"
        :emojiSize="18"
        :data="indexFiltered"
        ref="flags"
      />
    </div>
    <div class="row">
      <button @click="toggleFlagsVisible">
        Show / hide the flags picker (with v-show)
      </button>
    </div>
  </div>
</template>

<script>
import data from '../data/all.json'
import { Picker, EmojiIndex } from '../src'
import '../css/emoji-mart.css'

let indexFiltered = new EmojiIndex(data, {
  emojisToShowFilter: (emoji) => {
    return emoji.short_names[0].match(/^flag.*/) !== null
  },
})

export default {
  data() {
    return {
      indexFiltered: indexFiltered,
      activeSet: 'native',
      emoji: 'point_up',
      title: 'Pick your emoji',
      isVisible: true,
      emojiPickerDialog: false,
      emojisOutput: '',
      flagsVisible: true,
    }
  },
  methods: {
    toggleFlagsVisible() {
      this.flagsVisible = !this.flagsVisible
      if (!this.flagsVisible) {
        this.$refs.flags.onAnchorClick(this.$refs.flags.categories[0])
      }
    },
  },
  components: {
    Picker,
  },
}
</script>

**Comment by aldinezi** [comment]
Awesome. Works perfectly fine with `onAnchorClick`.
