### ISSUE TITLE
emojiSize is ignored; always 24

### ISSUE THREAD

**Issue by sadtaco** [serebrov/emoji-mart-vue#66]
Removed. Figured out the problem with "emojiSize" is that jQuery puts attributes to lower case. I needed to write the property as emoji-size

**Comment by serebrov** [comment]
OK, thanks for the update.

Initial issue, for reference:

> The docs list emojiSize as a property with a default of 24.
> When I try...
> <picker :data="emojiIndex" emojiSize="32" size="32" set="twitter" title="Select an emoji" emoji="arrow_up" />
> the resulting html is <div class="emoji-mart" style="width: 355px;" emojisize="32" size="32">
> I have the Vue inspector installed, and in there I can see the component is still emojiSize: 24 as well.
> The other properties set fine. I can't figure out what's wrong with this one.
