### ISSUE TITLE
Garbage remains in the emoji image. 

### ISSUE THREAD

**Issue by magita** [serebrov/emoji-mart-vue#68]
Thank you for a good library.

Garbage is left in the emoji image as shown by the red circle in the screenshot.
Can't be removed it well?
![screenshot](https://user-images.githubusercontent.com/1767950/77055453-3fc53380-6a14-11ea-8069-c40602c73ceb.png)

**Comment by serebrov** [comment]
This looks like a CSS related issue, might be related to the styles for search results (it looks like the icons are shifting a bit when searching).

But I've just tried (Mac OS, Google Chrome) and I don't see it:

<img width="617" alt="Screenshot 2020-03-22 at 15 49 59" src="https://user-images.githubusercontent.com/597640/77251089-f7e11f00-6c54-11ea-8d53-777249b40aa4.png">

Please provide more details about the issue:
- Do you see this issue in the demo app at https://serebrov.github.io/emoji-mart-vue/?
- Browser and OS where you see the issue.
- Is the issue only reproduced during search?
- Is the issue only reproduced for twitter icons or for other sets too?

**Comment by magita** [comment]
Thank you for the quick reply. 

> Do you see this issue in the demo app at https://serebrov.github.io/emoji-mart-vue/?

Yes.

> Browser and OS where you see the issue.

Chrome + Windows10 -> not reproduced.
Chrome + MacOS Mojave -> always reproduce
Safari + MacOS Mojave -> reproduce by browser screen size

> Is the issue only reproduced during search?

No. It is reproduced in the Emoji-tag too.
`<emoji :data="emojiindex" emoji="white_heart" set="twitter" :size="32" />`

> Is the issue only reproduced for twitter icons or for other sets too?

It is reproduced for Apple icon, Facebook icon too.


https://jm-david.github.io/emoji-mart-vue/
Not reproduced here.

**Comment by magita** [comment]
Additional Information:
https://serebrov.github.io/emoji-mart-vue/
When I access this page, the issue reproduced with iOS + Safari.

**Comment by serebrov** [comment]
@magita I've just published version `7.0.1` with a fix to npm, please check how it works for you.

**Comment by magita** [comment]
Thank you for the quick response!
Emoji was displayed successfully!
