### ISSUE TITLE
Needing data if using native

### ISSUE THREAD

**Issue by LukeGarrigan** [serebrov/emoji-mart-vue#70]
So I have the general setup:

```
import { Picker, EmojiIndex } from 'emoji-mart-vue-fast';
...
public ei = new EmojiIndex(data, {recentLength: 8, exclude: ['flags', 'symbols']});


```
and in my vue template I have:
`<Picker :emoji-size="21" :perLine="9" :native="true" :showPreview="false" :data="ei" @select="insertEmoji" class="emoji-picker" v-show="emojiPickerOpen" ></Picker>
`

The question is: because I'm using `:native="true"` do I actually need to grab the emojis.json file?

**Comment by serebrov** [comment]
@LukeGarrigan yes, and you probably want the `all.json` - this is an actual database of emojis and related metadata, the `EmojiIndex` won't work without it.

Other json files might be beneficial if you were using a specific icons set, for example `apple` set - it doesn't include some of the icons, so in this case using `apple.json` might reduce the amount of included data a bit.

**Comment by LukeGarrigan** [comment]
Ah okay, I see my misunderstanding, thank you!
