### ISSUE TITLE
Cannot read property 'observe' of null

### ISSUE THREAD

**Issue by mdeprezzo** [serebrov/emoji-mart-vue#73]
Hi, i've switched from emoji-mart-vue to emoji-mart-vue-fast, but on the first load of the page, i recieve this message. While if i refresh the page all works fine.

```Cannot read property 'observe' of null```

what am i missing ?

**Comment by serebrov** [comment]
@mdeprezzo it is hard to say. I've just checked the demo app - https://serebrov.github.io/emoji-mart-vue/ and I don't see any errors.

**Comment by mdeprezzo** [comment]
Ok, maybe was my problem, with mounted. Now works fine. Thanks anyway, we
can closed the issue

Il lun 11 mag 2020, 11:24 Boris Serebrov <notifications@github.com> ha
scritto:
