### ISSUE TITLE
The skin property of EmojiData always equals null.

### ISSUE THREAD

**Issue by dzmitryoush** [serebrov/emoji-mart-vue#74]
The 'select' event always returns emojis with property 'skin' equal null.
And property 'colons' doesn't contain ':skin-tone-*:'.

Original repository doesn't exist this problem.

**Comment by serebrov** [comment]
@dzmitryoush thanks for reporting the issue, I've just pushed a 7.0.2 release with a fix. Please check if it works for you.

**Comment by dzmitryoush** [comment]
@serebrov thanks a lot. It works for me 👍
