### ISSUE TITLE
Change dialoug size

### ISSUE THREAD

**Issue by uwejan** [serebrov/emoji-mart-vue#76]
The emoji dialoug/box is over rendering , is there a way to controll the the position of the box?

**Comment by serebrov** [comment]
The look and size of the dialog can be changed with CSS, another option is to use slots in the picker component, there is a "Custom Search And Preview Templates Example" in the [demo app](https://serebrov.github.io/emoji-mart-vue/).

You can also check the [picker component source](https://github.com/serebrov/emoji-mart-vue/blob/master/src/components/Picker.vue). It is composed of smaller components (seach, categories, preview, etc), so it is not complex to use these smaller building blocks to make own picker component.

For example, here is how the picker looks in a project where I've used it:

<img width="297" alt="Screenshot 2020-07-13 at 23 32 42" src="https://user-images.githubusercontent.com/597640/87351853-b9a0a000-c562-11ea-8cc5-e8e0f000ba0a.png">

**Comment by uwejan** [comment]
perfect, thanks.
