### ISSUE TITLE
Switch to StaticPicker as a default component

### ISSUE THREAD

**Issue by serebrov** [serebrov/emoji-mart-vue#80]
Currently, the `Picker` component uses virtual scroller for additional performance, although it also is a source of issues (#50, #57, #77).

At the same time, as I remember, it didn't add significant performance boost, so it should be OK if the default `Picker` was "static" (not using the virtual scroller) and we could keep and additional `VirtualScrollPicker` component as a more performant option, for the cases where this is really needed.

**Comment by PVince81** [comment]
In some scenario, from which I couldn't isolate the impacting components, using `Picker` also causes a permanent CPU load (reported as "Medium impact" by Firefox) as long as the tab is visible, even when the picker is not open yet. I guess there's something with the DynamicScroller that might work in the background.

See https://github.com/nextcloud/spreed/issues/4501

It was not reproducible in other simpler page embedding scenarios, so I didn't raise an issue for it.

**Comment by serebrov** [comment]
Done and released in v8.0.1.
