### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by yourkostylev** [serebrov/emoji-mart-vue#81]
This error occurs when user switches between emoji categories by clicking top panel categories icons _and_ have filled search field.
This is for StaticPicker by the way.
![image](https://user-images.githubusercontent.com/22351022/88819721-0aea9980-d1c9-11ea-8385-bdfe074500af.png)

**Comment by serebrov** [comment]
Fixed in version 7.0.4.
Now there is no error (and no effect) when clicking the category anchor while search is active.
