### ISSUE TITLE
Vue3 support?

### ISSUE THREAD

**Issue by hirokai** [serebrov/emoji-mart-vue#88]
Is there any plan to support Vue3? If any, APIs have changed significantly in Vue3, and I wonder how simultaneous support for both Vue 2 and 3 will be realized.

I may want to contribute if possible.

**Comment by yoonasy** [comment]
me too

**Comment by serebrov** [comment]
I am interested indeed in adding a Vue 3 support, either as a universal library or by making a separate Vue 3 package. I know it has been released, but it is still an early stage and they promised to also port some V3 features back to V2 and also release a "migration build" which will be more backward compatible (not sure though if it is good to rely on it for a component, as the target application may not use the migration build).

Anyway, I haven't study this deeply, it might actually be not that complex to support both Vue versions, as while working on my version of emoji mart, I extracted most of the logic out of components, so they are a relatively thin layer on top of Vue-independent code (the [`EmojiIndex`](https://github.com/serebrov/emoji-mart-vue/blob/84ff64e51637cf4e8b241c07df5f4e7a50541399/src/utils/emoji-data.js#L97) and [`EmojiView`](https://github.com/serebrov/emoji-mart-vue/blob/84ff64e51637cf4e8b241c07df5f4e7a50541399/src/utils/emoji-data.js#L476) classes).

**Comment by serebrov** [comment]
After initial testing, there was a small issue in Vue 3, which is fixed and now the `Picker` component works in the Vue 3 app without major changes. Published version 8.0.1 with a fix.

I also added a [demo app with Vue 3 here](https://github.com/serebrov/emoji-mart-vue3-demo).

Not closing this issue yet for the case other problems are found.

**Comment by Alex-R-31** [comment]
> Not closing this issue yet for the case other problems are found.

Hi there. It appears I've found one. I'm currently using Vue 2 with Nuxt.js, and attempting to use version 8.0.1 causes the following errors to occur whenever I attempt to scroll within the component, or click one of the tabs at the top. As a note, I do use some custom emojis so that may affect it. Contact me if I can provide you with any other information!


![image](https://user-images.githubusercontent.com/46286597/106379248-7db81580-63a2-11eb-9028-2cc1568c1eb0.png)

**Comment by serebrov** [comment]
@Alex-R-31 Thanks for reporting it! I've just published version 8.0.3 with a fix. Can you check if it works for you?

**Comment by Alex-R-31** [comment]
@serebrov that's fixed it! Thanks for the speedy response.
